" install plugins

call plug#begin('~/.vim/plugged')

Plug 'Valloric/YouCompleteMe'
Plug 'SirVer/ultisnips'
Plug 'itchyny/lightline.vim'
" Commenting support (gc)
Plug 'tpope/vim-commentary'

" Fugitive
Plug 'tpope/vim-fugitive'
" " Git log viewer (Gitv! for file mode)
Plug 'gregsexton/gitv', { 'on': 'Gitv' }
" " Git changes showed on line numbers
Plug 'airblade/vim-gitgutter'
" " REST Console
" Plug 'diepm/vim-rest-console', { 'for': 'rest' }

" Surround (cs"')
Plug 'tpope/vim-surround'

" Colorschemes
Plug 'altercation/vim-colors-solarized'

" Add plugins to &runtimepath
call plug#end()	


let mapleader = " "
set backspace=2  " Backspace deletes like most programs in insert mode
set ruler         " show the cursor position all the time

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

" Numbers
set number
set numberwidth=5

"Colorscheme
syntax enable
set background=dark
colorscheme solarized
